### ISSUE TITLE
[ENHANCEMENT] Inverted PPM signal

### ISSUE THREAD

**Issue by pawelsky** [schinken/PPMEncoder#3]
Hi did you consider adding an option to generate inverted PPM signal? Could be configured by an additional parameter added to the begin method, e.g.:

`void begin(uint8_t outputPin, uint8_t numChannels, bool inv);`

Some RC systems do require an inverted PPM.

**Comment by schinken** [comment]
Hi @pawelsky,

cool idea! Never thought of it.
I've implemented this in "dry" - so I don't have any hardware to test that

https://github.com/schinken/PPMEncoder/commit/df1d42595e5241f5e31c8b901416c6d90f0f073b

Please feel free to test and report if it doesn't work! :)

**Comment by pawelsky** [comment]
Wow, that was quick!

Looks like it works. Here is the default signal
![image](https://user-images.githubusercontent.com/7121220/118409407-8fd86e00-b68a-11eb-8307-5ded320756b7.png)

And here is the inverted one
![image](https://user-images.githubusercontent.com/7121220/118409450-cb733800-b68a-11eb-9ef3-63f2ac5a87b4.png)

**Comment by schinken** [comment]
Thank you for the Logic-Output :) 

I think we can close this issue then. I already pushed a 0.3.0 release. According to Arduino-Libary-Docs, this should get pulled automatically - but it wasn't yet: https://www.arduino.cc/reference/en/libraries/ppmencoder/

Have fun with this library! :)
