### ISSUE TITLE
bier?

### ISSUE THREAD

**Issue by Benman2785** [schinken/PPMEncoder#4]
bitte nach Berlin schicken

**Comment by Benman2785** [comment]
sry - fc

**Comment by schinken** [comment]
haha made my day :)

**Comment by Benman2785** [comment]
leider verstehe ich deinen Code nicht - kannst du bitte etwas mehr dokumentieren?

**Comment by schinken** [comment]
@Benman2785 Was genau willst denn wissen?

**Comment by Benman2785** [comment]
hört sich etwas strange an -> aber habs hinbekommen.

sry für die späte Antwort :)

**Comment by schinken** [comment]
na das is doch gut :D und wo ist jetzt das bier?

**Comment by Benman2785** [comment]
na ich bin morgen wieder in Berlin - können uns ja Gesundbrunnen treffen und ich gebe dir eins aus ;)

**Comment by schinken** [comment]
Is nur knapp 5h von mir weg. ne lass mal :D

**Comment by Benman2785** [comment]
wenn du mal da bist schreib mich an - bekommst dann auch ne Currywurst mit Bierchen ;)
